### ISSUE TITLE
[Feature Request]_Rework_assetIdent

### ISSUE THREAD

**Issue by Lypsolon** [ynput/ayon-usd-resolver#18]
### Description

This feature aims to rework assetIdent to expand its functionality as a cacheEntety and make it easier to use and more versatile. 

Link to the current Struct
https://github.com/ynput/ayon-usd-resolver/blob/8e681a95b756ed0cf458bb14f9d10a785c87de22/src/AyonUsdResolver/resolverContextCache.h#L19

## cache entity re-evaluation
Currently, we cannot invalidate a cache entity so that it gets re-evaluated when encountered. 

## file structures 
We should move the cache entity object to its file to keep every file isolated for its purpose. 

### Proposed Solution

Add a function re_evaluate() 
and add private variables to make sure the function is the main way of getting the data. 

### Alternatives Considered

Global or per object invalidation via external calls (already implemented via [removeCachedObject](https://github.com/ynput/ayon-usd-resolver/blob/8e681a95b756ed0cf458bb14f9d10a785c87de22/src/AyonUsdResolver/resolverContextCache.h#L91) and [clearCache](https://github.com/ynput/ayon-usd-resolver/blob/8e681a95b756ed0cf458bb14f9d10a785c87de22/src/AyonUsdResolver/resolverContextCache.h#L96) respectively) but its means that cache invalidation need to be done from the outside. 

### Is there an existing issue with this?

- [X] I have searched the existing issues

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

**Comment by Lyon-Rosenblatt-Ynput** [comment]
Let's consider adding a handle to store what root_replace option has been used within the cache_entety. 

- this will need to be a key for the [siteRoots unordert_map](https://github.com/ynput/ayon-cpp-api/blob/5e2ffd77e486d05036327c9e2941d4270b151477/src/AyonCppApi/AyonCppApi.h#L170)
- we could store a vector along the resolver so that it can store a u_int8t index instead of a string_key. This would also make disconnecting the AyonCppApi easier.

**Comment by Lyon-Rosenblatt-Ynput** [comment]
There should be an option to mark an asset_itent as static when it is constructed so that it can not be overwritten. 

- this would be good to have for pinning_file support 
- this should be immutable, as lazy handling of this would allow for some sketchy setups, and there should not be a case where you don't know if it is static before creation.
